
import java.text.DecimalFormat;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Yisroel
 */
public class gradeCaluculatorGui extends javax.swing.JFrame {
    
    
     
    public gradeCaluculatorGui() {
        initComponents();
    }
    
    public static double computeMean (double[] gradeRecord, int i){
        double sum =0;
        for (int n = 0; n < i; n++) {
        sum += gradeRecord[n];
    }
    return sum / i;
    }
    
    public static double computeMedian(double[] gradeRecord, int i) {
         //Important sort first!!!!!!
         Arrays.sort(gradeRecord, 0, i);
        int middle = i/2;
        if (i%2 == 1) {
        return gradeRecord[middle];
    } else {
        return (gradeRecord[middle-1] + gradeRecord[middle]) / 2.0;
    }
}
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGradeNum = new javax.swing.JLabel();
        lblGradeMean = new javax.swing.JLabel();
        lblGradeMedian = new javax.swing.JLabel();
        txtGradeNum = new javax.swing.JTextField();
        txtGradeMean = new javax.swing.JTextField();
        txtGradeMedian = new javax.swing.JTextField();
        btnEntrGrades = new javax.swing.JButton();
        btnExit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGradeNum.setText("Number of Grades Entered");

        lblGradeMean.setText("Mean of Grades");

        lblGradeMedian.setText("Median of Grades");

        btnEntrGrades.setText("Enter Grades");
        btnEntrGrades.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrGradesActionPerformed(evt);
            }
        });

        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblGradeMedian, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGradeMean, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblGradeNum, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnEntrGrades, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtGradeMean)
                        .addComponent(txtGradeNum)
                        .addComponent(txtGradeMedian, javax.swing.GroupLayout.DEFAULT_SIZE, 91, Short.MAX_VALUE))
                    .addComponent(btnExit, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblGradeNum, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtGradeNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addComponent(lblGradeMean, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtGradeMean, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lblGradeMedian, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                    .addComponent(txtGradeMedian))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntrGrades)
                    .addComponent(btnExit))
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnEntrGradesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrGradesActionPerformed
        // create the variables and any needed modifiers 
        DecimalFormat df = new DecimalFormat("#0.0##");
        
        String input = null;
        double mean;
        double median;
        int i = 0;
        
        //create array
        final int GRADES_LENGTH = 25;
        double[] gradeRecord = new double[GRADES_LENGTH];
        
        //now create the imput for the array and the loop
         do 
        {
            try
            {
               input=JOptionPane.showInputDialog (this, "Enter Grade.","Enter Grade", 
               JOptionPane.PLAIN_MESSAGE);
               if (input != null && input.length() > 0) 
               {
                   gradeRecord[i] = Double.parseDouble(input);
                    i++; 
               }
               if (i > 24) 
               {
                   JOptionPane.showMessageDialog(this, "You can only input 25 values!!","Too Much Data!",
                   JOptionPane.ERROR_MESSAGE);
               }
            }
            catch (NumberFormatException e) 
            {
                JOptionPane.showMessageDialog(this, "Your input must be numeric!","Invalid Data!",
                JOptionPane.ERROR_MESSAGE);
            }
        } while (input != null && input.length() > 0);
         
         txtGradeNum.setText(Integer.toString(i));
         
         mean = computeMean(gradeRecord, i);
         txtGradeMean.setText(df.format(mean));
         txtGradeMean.setText(Double.toString(mean));
         
         median = computeMedian(gradeRecord, i);
         txtGradeMedian.setText(df.format(median));
         txtGradeMedian.setText(Double.toString(median));
         
        
    }//GEN-LAST:event_btnEntrGradesActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(gradeCaluculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(gradeCaluculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(gradeCaluculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(gradeCaluculatorGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new gradeCaluculatorGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEntrGrades;
    private javax.swing.JButton btnExit;
    private javax.swing.JLabel lblGradeMean;
    private javax.swing.JLabel lblGradeMedian;
    private javax.swing.JLabel lblGradeNum;
    private javax.swing.JTextField txtGradeMean;
    private javax.swing.JTextField txtGradeMedian;
    private javax.swing.JTextField txtGradeNum;
    // End of variables declaration//GEN-END:variables
}
